version: '3.8'

services:
  # Optional: Local PostgreSQL for development
  # You can also use Neon PostgreSQL directly
  db:
    image: postgres:15
    container_name: packex_postgres
    environment:
      POSTGRES_USER: packex_user
      POSTGRES_PASSWORD: packex_password
      POSTGRES_DB: packex_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # PackEx application with UploadThing
  app:
    build: .
    container_name: packex_app
    ports:
      - "3000:3000"
    environment:
      # Use local database (comment out to use Neon)
      DATABASE_URL: "postgresql://packex_user:packex_password@db:5432/packex_db?schema=public"
      
      # UploadThing Configuration
      UPLOADTHING_TOKEN: "${UPLOADTHING_TOKEN}"
      
      # Application Settings
      NODE_ENV: "production"
      SESSION_SECRET: "${SESSION_SECRET}"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
